#------------------------------------------
# 1. docker-compose -p microservices-comp3095-ecommerce -f docker-compose.yml up -d
# --- this command will start the containers in detached mode without rebuilding the images
#
#2. docker-compose -p microservices-comp3095-ecommerce -f docker-compose.yml up -d --build
#-- this command forces the rebuild of images even if the image already exists
#------------------------------------------------
version: '3.9'

services:

  product-service:
    image: product-service
    ports:
      - "8082:8082"
    build:
      context: ./product-service
      dockerfile: ./Dockerfile
    container_name: product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
    networks:
      - spring


  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGO-INITDB_ROOT_USERNAME=admin
      - MONGO-INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo/products:/data/db
      - ./init/mongo/doocker-entrypoint-initdb.d/mongo-init.js:/doocker-entrypoint-initdb.d/mongo-init.js
    #restart: unless-stopped
    #command:
    #  - mongod -auth
    networks:
      - spring


  mongo-express:
    image: mongo-express
    ports:
      - "8084:8084"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    container_name: mongo-express
    depends_on:
      - mongodb
    networks:
      - spring

volumes:
  mongo-db:
    driver: local


networks:
  spring:
    driver: bridge



